### ISSUE TITLE
Tinker's construct (1.6.4)

### ISSUE THREAD

**Issue by Frontrider** [EXTER7/Foundry#12]
TiC does not recognises Foundry molten metals as molten metals, and foundry does the same for TiC.

Could you register them in the fluid regisry more properly?

If i have to choose between TiC and foundry, i choose TiC.

![2014-05-28_14 20 04](https://cloud.githubusercontent.com/assets/6755034/3104120/a34dc5de-e662-11e3-9a9b-fe027b6ac054.png)

Tinker's construct not even tries to produce foundry liquid metals (you say that its do), and foundry not recognises TiC metals...

The config related to it:
integration {
    B:enable.buildcraft=false
    B:enable.forestry=false
    B:enable.gregtech=false
    B:enable.ic2=false
    B:enable.railcraft=true
    B:enable.redarsenal=true
    B:enable.te3=true
    B:enable.ticon=true
    B:gregtech.change_recipes=false
}

**Comment by EXTER7** [comment]
This issue has been fixed in the 1.0.0.0 builds. TiC liquid metals works in the Metal Caster, and Foundry liquid metals works in TiC's Casting Table/Basin as well.
