### ISSUE TITLE
[Enhancment] more input slots on Alloy Furnace

### ISSUE THREAD

**Issue by Frontrider** [EXTER7/Foundry#18]
i did not tried it yet (I'm making a pack for a few people around me so i try stable mods) but if you want more mod interaction in the future, i could suggest 3 input slots (ender io alloys), and maybe fluid input (things like signalum, enderium if you got what i mean).

**Comment by EXTER7** [comment]
The Alloy Furnace is a starting tier machine to get simple alloys for machine components. For more advanced alloys, there's the Alloy Mixer which makes alloys with liquid metals and has 4 slots.

**Comment by Frontrider** [comment]
close it.
