### ISSUE TITLE
Refactory Hopper deletes contents when mined

### ISSUE THREAD

**Issue by drz2k** [EXTER7/Foundry#29]
Just a warning I guess since it's a foundry issue I'm assuming, but if you mine (to pick up) a refactory hopper, it will delete everything inside it, including any tanks you had inside draining. It doesn't drop it's item contents like chests do, nor does it preserve it's fluid contents (although that may be intended).

https://github.com/Hypovolemia/hypovolemia/issues/38

**Comment by EXTER7** [comment]
The Refractory Hopper isn't meant to store fluids. Any fluid left inside will be lost. However items not dropping when breaking a hopper is a bug and will soon be fixed.
