### ISSUE TITLE
crashes dedicated  multiplayer server with forge build 1521 on startup while looking for client side classes. I suggest double checking your sided proxies (directives)

### ISSUE THREAD

**Issue by kreezxil** [EXTER7/Foundry#31]
Issue: crashes dedicated  multiplayer server with forge build 1521 on startup while looking for client side classes. I suggest double checking your sided proxies (directives)

crash report:
https://gist.github.com/39a81e5750ac5fdb2e29

fml server latest:
https://gist.github.com/6efef77aa2bca8369606

P.S. The client loads fine however. with no issues.

**Comment by EXTER7** [comment]
This has already been fixed in the lastest source.

**Comment by kreezxil** [comment]
Thanks.
