### ISSUE TITLE
Server Crash with SpongeForge

### ISSUE THREAD

**Issue by phit** [EXTER7/Foundry#35]
crashes on launch

spongeforge 1.8.9 BETA-1049
foundry 1.3.2.0

[crash-2016-01-13_12.16.43-server.txt](https://github.com/EXTER7/Foundry/files/89234/crash-2016-01-13_12.16.43-server.txt)

**Comment by EXTER7** [comment]
Seems to be an issue with SpongeForge. Try reporting this in the SpongeForge repository.

**Comment by gabizou** [comment]
The current workaround (we have a feature we're working on for mixins to make this workaround obsolete) is to have any `IProperty` instances at least extend `net.minecraft.block.properties.PropertyHelper`. That way our casing back and forth works without a hitch.
