### ISSUE TITLE
buildcraft compatibility crash

### ISSUE THREAD

**Issue by meelock** [EXTER7/Foundry#38]
yeah... I should probably just ask them to update their API, but they appear really busy right now. so basically, can you add back compatibility for the unofficial API?

if you can that would be really nice... :P

**Comment by EXTER7** [comment]
Builcraft has been updated to use the official RF API.

[BC 7.2.0 releases](https://github.com/AlexIIL/BC-Temp-releases)

**Comment by meelock** [comment]
Yay! thanks, I was probably just being derpy. :P well, that's what sleep depravity does to ya.
