### ISSUE TITLE
Liquid Iron not Fluid Registered?

### ISSUE THREAD

**Issue by Phonavis** [EXTER7/Foundry#42]
I was attempting to make some steel, and I noticed I couldn't use the Molten Iron from ticon as a substitute for Liquid Iron, was this intentional or just a bug?

**Comment by EXTER7** [comment]
Tinker's fluids are not supported in the MC-1.8.9 version at the moment but will soon be added back.

**Comment by EXTER7** [comment]
The latest MC-1.8.9 release of now has TiCon integration.
