### ISSUE TITLE
Enhancement Request: Make TiCon casts usable in the Caster

### ISSUE THREAD

**Issue by ghost** [EXTER7/Foundry#47]
Sometimes the TiCon smelter is inconvenient and detracts from my enjoyment. I've been looking for a new way to make parts. Can we have the Metal Caster accept TiCon casts or have the ability to make molds that match the casts?

**Comment by medsal15** [comment]
Yes, bring it back from the 1.7.10 version please.

**Comment by EXTER7** [comment]
Both MC-1.8 and MC-1.9 versions of Foundry now have TiCon integration.
