### ISSUE TITLE
[1.8.9] Crash on startup: java.lang.IllegalArgumentException: Casting recipe result is not of a valid class.

### ISSUE THREAD

**Issue by BBoldt** [EXTER7/Foundry#49]
https://gist.github.com/c8ec1d58bd9acd7a3c09ea258d1b88f4

Forge 1808
Foundry 1.4.1.0
Tinkers' Construct 2.2.1

**Comment by BBoldt** [comment]
Damn that was quick!

Thanks!

**Comment by BBoldt** [comment]
Actually, another crash with 1.4.1.1:

https://gist.github.com/ee2c4ae04b4163579d82063050892b90

@EXTER7

**Comment by EXTER7** [comment]
Released 1.4.1.2, which fixes that crash.
