### ISSUE TITLE
Crash when right clicking with a refractory fluid container in world 1.10.2

### ISSUE THREAD

**Issue by MysticAura** [EXTER7/Foundry#56]
When you right click in world while holding a refractory fluid container (mine was full of platinum), the game instantly crashes.

MC Version: 1.10.2
Forge Version: 12.18.0.2007
Foundry Version: 1.10.2-2.0.0.0

[Crash Log](http://pastebin.com/5V0XqF5p)

**Comment by EXTER7** [comment]
This has been fixed in the 2.0.0.1 release.
