### ISSUE TITLE
Conflict with Tconstruct during Init Phase 1.10.2 - Foundry 2.1 & Tcon 2.3.3a

### ISSUE THREAD

**Issue by t3f** [EXTER7/Foundry#61]
<snip>
[B#347]  [20:27:34] [Client thread/ERROR] [FML]: Caught exception from foundry
[B#347]  java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/smeltery/ICastingRecipe
[B#347]     at exter.foundry.ModFoundry.preInit(ModFoundry.java:111) ~[ModFoundry.class:?]
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
[B#347]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
[B#347]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
</snip>

Full GIST @ https://gist.github.com/t3f/237f038ec86cabfe81495b80f5396600

**Comment by Moustik2002** [comment]
I confirm it, same thing happens here : http://pastebin.com/c0gJzuku

**Comment by medsal15** [comment]
And I thought it was Tconstruct's fault. Seems I was wrong.

**Comment by EXTER7** [comment]
Foundry version 2.1.0.1 is now released with TiCon integration reverted to TiCon 2.3. If you have TiCon 2.4, use Foundry version 2.1.0.0 instead.
